FROM openjdk:8
COPY target/ModuloMantenimiento-1.0.0.jar /usr/src/proyectoFinalFinalisimo/
WORKDIR /usr/src/proyectoFinalFinalisimo/
CMD ["java","-jar","/usr/src/proyectoFinalFinalisimo/ModuloMantenimiento-1.0.0.jar"]
