FROM openjdk:8
COPY target/ModuloEvaluacionEstudiantes-1.0.jar /usr/src/proyectoFinalFinalisimo/
WORKDIR /usr/src/proyectoFinalFinalisimo/
CMD ["java","-jar","/usr/src/proyectoFinalFinalisimo/ModuloEvaluacionEstudiantes-1.0.jar"]
